import { APIRequestError, requestAPIData } from '@/lib/api/client'
import type { WeatherConfidence, WeatherConfidenceLevel, WeatherContextRequest, WeatherContextResponse, WeatherMetricSummary, WeatherNotice } from '@/types/weather-context'

const levels = new Set<WeatherConfidenceLevel>(['none', 'low', 'medium', 'high'])

export async function getWeatherContext(request: WeatherContextRequest): Promise<WeatherContextResponse> {
  const trajectoryID = uuid(request.trajectoryID, 'trajectoryID')
  const asOfTime = timestamp(request.asOfTime, 'asOfTime')
  if (!Number.isInteger(request.durationSeconds) || request.durationSeconds < 1) throw new APIRequestError('Weather Context duration must be a positive whole number of seconds.')
  const searchParams = new URLSearchParams({ as_of_time: asOfTime, duration_seconds: String(request.durationSeconds) })
  return parseResponse(await requestAPIData<unknown>(`/api/v1/trajectories/${encodeURIComponent(trajectoryID)}/weather-context`, { signal: request.signal, searchParams, timeoutMilliseconds: 20_000 }))
}

function parseResponse(value: unknown): WeatherContextResponse {
  const root = record(value, 'response'); const weather = record(root.weather, 'weather'); const trust = record(root.trust, 'trust'); const alignment = record(root.alignment, 'alignment'); const encounter = record(root.encounter, 'encounter'); const uncertainty = record(root.uncertainty, 'uncertainty')
  const trajectoryID = uuid(text(root.trajectory_id, 'trajectory_id'), 'trajectory_id'); const asOfTime = timestamp(root.as_of_time, 'as_of_time')
  return {
    version: text(root.version, 'version'), trajectory_id: trajectoryID, as_of_time: asOfTime,
    weather: { schema_version: text(weather.schema_version,'weather.schema_version'), status:text(weather.status,'weather.status'), trajectory_id:sameUUID(weather.trajectory_id,trajectoryID,'weather.trajectory_id'), as_of_time:sameTime(weather.as_of_time,asOfTime,'weather.as_of_time'), samples:list(weather.samples,'weather.samples').map((item,index)=>parseSample(item,index)), confidence:confidence(weather.confidence,'weather.confidence'), limitations:list(weather.limitations,'weather.limitations').map((item,index)=>{const x=record(item,`weather.limitations[${index}]`);return{code:text(x.code,`weather.limitations[${index}].code`),message:text(x.message,`weather.limitations[${index}].message`),scope:optionalText(x.scope,`weather.limitations[${index}].scope`)??''}}), explanations:notices(weather.explanations,'weather.explanations'), scope_guard:text(weather.scope_guard,'weather.scope_guard'), input_fingerprint:fingerprint(weather.input_fingerprint,'weather.input_fingerprint'), source_names:list(weather.source_names,'weather.source_names').map((item,index)=>text(item,`weather.source_names[${index}]`)), latest_available_at:timestamp(weather.latest_available_at,'weather.latest_available_at'), generated_at:timestamp(weather.generated_at,'weather.generated_at') },
    trust: { version:text(trust.version,'trust.version'),decision:text(trust.decision,'trust.decision'),usable:booleanValue(trust.usable,'trust.usable'),as_of_time:sameTime(trust.as_of_time,asOfTime,'trust.as_of_time'),score:ratio(trust.score,'trust.score'),components:list(trust.components,'trust.components').map((item,index)=>{const x=record(item,`trust.components[${index}]`);return{name:text(x.name,`trust.components[${index}].name`),score:ratio(x.score,`trust.components[${index}].score`),weight:ratio(x.weight,`trust.components[${index}].weight`)}}),allowed_scopes:list(trust.allowed_scopes,'trust.allowed_scopes').map((item,index)=>text(item,`trust.allowed_scopes[${index}]`)),limitations:notices(trust.limitations,'trust.limitations'),explanations:notices(trust.explanations,'trust.explanations'),input_fingerprint:fingerprint(trust.input_fingerprint,'trust.input_fingerprint') },
    alignment: { version:text(alignment.version,'alignment.version'),status:text(alignment.status,'alignment.status'),trajectory_id:sameUUID(alignment.trajectory_id,trajectoryID,'alignment.trajectory_id'),as_of_time:sameTime(alignment.as_of_time,asOfTime,'alignment.as_of_time'),trust_decision:text(alignment.trust_decision,'alignment.trust_decision'),trust_score:ratio(alignment.trust_score,'alignment.trust_score'),point_count:whole(alignment.point_count,'alignment.point_count'),aligned_count:whole(alignment.aligned_count,'alignment.aligned_count'),unmatched_count:whole(alignment.unmatched_count,'alignment.unmatched_count'),coverage_ratio:ratio(alignment.coverage_ratio,'alignment.coverage_ratio'),matches:list(alignment.matches,'alignment.matches'),limitations:notices(alignment.limitations,'alignment.limitations'),explanations:notices(alignment.explanations,'alignment.explanations'),input_fingerprint:fingerprint(alignment.input_fingerprint,'alignment.input_fingerprint'),generated_at:timestamp(alignment.generated_at,'alignment.generated_at') },
    encounter: { version:text(encounter.version,'encounter.version'),status:text(encounter.status,'encounter.status'),trajectory_id:sameUUID(encounter.trajectory_id,trajectoryID,'encounter.trajectory_id'),as_of_time:sameTime(encounter.as_of_time,asOfTime,'encounter.as_of_time'),alignment_status:text(encounter.alignment_status,'encounter.alignment_status'),alignment_coverage_ratio:ratio(encounter.alignment_coverage_ratio,'encounter.alignment_coverage_ratio'),point_count:whole(encounter.point_count,'encounter.point_count'),encounter_point_count:whole(encounter.encounter_point_count,'encounter.encounter_point_count'),unprofiled_point_count:whole(encounter.unprofiled_point_count,'encounter.unprofiled_point_count'),profile_coverage_ratio:ratio(encounter.profile_coverage_ratio,'encounter.profile_coverage_ratio'),temperature_celsius:metric(encounter.temperature_celsius,'encounter.temperature_celsius'),precipitation_millimeters:metric(encounter.precipitation_millimeters,'encounter.precipitation_millimeters'),cloud_cover_percent:metric(encounter.cloud_cover_percent,'encounter.cloud_cover_percent'),wind_speed_meters_per_second:metric(encounter.wind_speed_meters_per_second,'encounter.wind_speed_meters_per_second'),wind_gusts_meters_per_second:metric(encounter.wind_gusts_meters_per_second,'encounter.wind_gusts_meters_per_second'),wind_direction_degrees:direction(encounter.wind_direction_degrees,'encounter.wind_direction_degrees'),limitations:notices(encounter.limitations,'encounter.limitations'),explanations:notices(encounter.explanations,'encounter.explanations'),input_fingerprint:fingerprint(encounter.input_fingerprint,'encounter.input_fingerprint'),generated_at:timestamp(encounter.generated_at,'encounter.generated_at') },
    uncertainty: { version:text(uncertainty.version,'uncertainty.version'),status:text(uncertainty.status,'uncertainty.status'),trajectory_id:sameUUID(uncertainty.trajectory_id,trajectoryID,'uncertainty.trajectory_id'),as_of_time:sameTime(uncertainty.as_of_time,asOfTime,'uncertainty.as_of_time'),severity_score:ratio(uncertainty.severity_score,'uncertainty.severity_score'),weather_multiplier:nonNegative(uncertainty.weather_multiplier,'uncertainty.weather_multiplier'),point_adjustments:list(uncertainty.point_adjustments,'uncertainty.point_adjustments'),limitations:notices(uncertainty.limitations,'uncertainty.limitations'),explanations:notices(uncertainty.explanations,'uncertainty.explanations'),input_fingerprint:fingerprint(uncertainty.input_fingerprint,'uncertainty.input_fingerprint'),generated_at:timestamp(uncertainty.generated_at,'uncertainty.generated_at') },
    input_fingerprint:fingerprint(root.input_fingerprint,'input_fingerprint'),generated_at:timestamp(root.generated_at,'generated_at')
  }
}
function parseSample(value:unknown,index:number){const field=`weather.samples[${index}]`;const item=record(value,field);const position=record(item.position,`${field}.position`);const source=record(item.source,`${field}.source`);return{sequence:whole(item.sequence,`${field}.sequence`),position:{latitude:bounded(position.latitude,`${field}.position.latitude`,-90,90),longitude:bounded(position.longitude,`${field}.position.longitude`,-180,180),...(position.altitude_meters==null?{}:{altitude_meters:numberValue(position.altitude_meters,`${field}.position.altitude_meters`)}),vertical_reference:text(position.vertical_reference,`${field}.position.vertical_reference`)},source:{provider:text(source.provider,`${field}.source.provider`),dataset:text(source.dataset,`${field}.source.dataset`),evidence_kind:text(source.evidence_kind,`${field}.source.evidence_kind`),...(source.horizontal_resolution_kilometers==null?{}:{horizontal_resolution_kilometers:nonNegative(source.horizontal_resolution_kilometers,`${field}.source.horizontal_resolution_kilometers`)}),temporal_resolution_seconds:whole(source.temporal_resolution_seconds,`${field}.source.temporal_resolution_seconds`)},features:record(item.features,`${field}.features`),valid_at:timestamp(item.valid_at,`${field}.valid_at`),available_at:timestamp(item.available_at,`${field}.available_at`),retrieved_at:timestamp(item.retrieved_at,`${field}.retrieved_at`)}}
function confidence(value:unknown,field:string):WeatherConfidence{const item=record(value,field);const level=text(item.level,`${field}.level`) as WeatherConfidenceLevel;if(!levels.has(level))invalid(`${field}.level is unsupported.`);return{score:ratio(item.score,`${field}.score`),level,reasons:list(item.reasons,`${field}.reasons`).map((value,index)=>{const reason=record(value,`${field}.reasons[${index}]`);return{code:text(reason.code,`${field}.reasons[${index}].code`),message:text(reason.message,`${field}.reasons[${index}].message`),contribution:numberValue(reason.contribution,`${field}.reasons[${index}].contribution`)}})}}
function metric(value:unknown,field:string):WeatherMetricSummary{const item=record(value,field);return{present_count:whole(item.present_count,`${field}.present_count`),coverage_ratio:ratio(item.coverage_ratio,`${field}.coverage_ratio`),...(item.minimum==null?{}:{minimum:numberValue(item.minimum,`${field}.minimum`)}),...(item.maximum==null?{}:{maximum:numberValue(item.maximum,`${field}.maximum`)}),...(item.mean==null?{}:{mean:numberValue(item.mean,`${field}.mean`)})}}
function direction(value:unknown,field:string){const item=record(value,field);return{present_count:whole(item.present_count,`${field}.present_count`),coverage_ratio:ratio(item.coverage_ratio,`${field}.coverage_ratio`),...(item.mean_direction_degrees==null?{}:{mean_direction_degrees:numberValue(item.mean_direction_degrees,`${field}.mean_direction_degrees`)}),...(item.concentration==null?{}:{concentration:ratio(item.concentration,`${field}.concentration`)})}}
function notices(value:unknown,field:string):WeatherNotice[]{return list(value,field).map((entry,index)=>{const item=record(entry,`${field}[${index}]`);return{code:text(item.code,`${field}[${index}].code`),message:text(item.message,`${field}[${index}].message`)}})}
function sameUUID(value:unknown,expected:string,field:string){const result=uuid(text(value,field),field);if(result!==expected)invalid(`${field} does not match the aggregate trajectory.`);return result}
function sameTime(value:unknown,expected:string,field:string){const result=timestamp(value,field);if(Date.parse(result)!==Date.parse(expected))invalid(`${field} does not match the aggregate time.`);return result}
function record(value:unknown,field:string):Record<string,unknown>{if(typeof value!=='object'||value===null||Array.isArray(value))invalid(`${field} must be an object.`);return value as Record<string,unknown>}
function list(value:unknown,field:string):unknown[]{if(!Array.isArray(value))invalid(`${field} must be an array.`);return value}
function text(value:unknown,field:string):string{if(typeof value!=='string'||value.trim()==='')invalid(`${field} must be a non-empty string.`);return value}
function optionalText(value:unknown,field:string){if(value==null)return undefined;if(typeof value!=='string')invalid(`${field} must be a string.`);return value}
function booleanValue(value:unknown,field:string){if(typeof value!=='boolean')invalid(`${field} must be boolean.`);return value}
function numberValue(value:unknown,field:string){if(typeof value!=='number'||!Number.isFinite(value))invalid(`${field} must be finite.`);return value}
function nonNegative(value:unknown,field:string){const result=numberValue(value,field);if(result<0)invalid(`${field} must not be negative.`);return result}
function whole(value:unknown,field:string){const result=nonNegative(value,field);if(!Number.isInteger(result))invalid(`${field} must be a whole number.`);return result}
function ratio(value:unknown,field:string){const result=numberValue(value,field);if(result<0||result>1)invalid(`${field} must be between zero and one.`);return result}
function bounded(value:unknown,field:string,min:number,max:number){const result=numberValue(value,field);if(result<min||result>max)invalid(`${field} is outside its allowed range.`);return result}
function timestamp(value:unknown,field:string){const result=text(value,field);if(Number.isNaN(Date.parse(result)))invalid(`${field} must be a valid timestamp.`);return result}
function uuid(value:string,field:string){const result=value.trim().toLowerCase();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(result))invalid(`${field} must be a valid UUID.`);return result}
function fingerprint(value:unknown,field:string){const result=text(value,field);if(!/^sha256:[0-9a-f]{64}$/.test(result))invalid(`${field} must be a SHA-256 fingerprint.`);return result}
function invalid(message:string):never{throw new APIRequestError(`The Weather Context response is invalid: ${message}`)}
